name: mahdavitasks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter_svg: ^2.0.7
  flutter:
    sdk: flutter

  shamsi_date: ^1.0.0
  intl: ^0.20.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf
    - family: IranNastaliq
      fonts:
        - asset: assets/fonts/IranNastaliq.ttf
        
  assets:
    - assets/images/mahdi.jpg
    - assets/images/BackGround.jpeg
    - assets/images/smooth_green_gradient.png
    - assets/images/IslamicButton.png
    - assets/icons/arrow_left.svg