name: mahdavitasks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flip_board: 
    git:
      url: https://github.com/cc-nogueira/flip_board.git
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf
    - family: IranNastaliq
      fonts:
        - asset: assets/fonts/IranNastaliq.ttf
        
  assets:
    - assets/images/mahdi.jpg
    - assets/images/BackGround.jpeg
    - assets/images/smooth_green_gradient.png

